obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]
inflation_radius: 0.55
observation_sources: laser_scan_sensor
laser_scan_sensor:
  data_type: LaserScan
  topic: /car_1/scan
  marking: true
  clearing: true
