DWAPlannerROS:
  max_vel_x: 1.5
  min_vel_x: 0.0
  max_trans_vel: 1.5
  min_trans_vel: 0.1
  max_rot_vel: 2.0
  min_rot_vel: 0.4
  acc_lim_x: 2.5
  acc_lim_theta: 3.2

  sim_time: 1.7
  vx_samples: 20
  vtheta_samples: 40

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01

  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  publish_traj_pc: true
  publish_cost_grid_pc: false
