global_costmap:
  global_frame: map
  robot_base_frame: car_1_base_link
  update_frequency: 2.0
  static_map: true
  resolution: 0.05
  transform_tolerance: 0.5

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
